### PR TITLE
feat: Added `Table.list_columns_with_missing_values`

### LINKED ISSUE #44: Inferred schema should know which columns have missing values
### Is your feature request related to a problem? Please describe

The inferred schema of a `Table` currently treat columns of type `X` with and without missing values the same. For example, in the following table both columns would get type `int`:

|a|b|
|-|-|
|1|1|
|2| |

### Desired solution

1. There is already a class `OptionalColumnType` but it's not used. It should be used to clearly mark columns with missing values. 
2. Add an abstract method `is_missing` or `may_be_missing` to `ColumnType`.
3. Implement it for the subclasses.
4. Use this method to reimplement `Table.list_columns_with_missing_values` and `Column.has_missing_values`.

### PR DESCRIPTION
**Pull request by Marsmaennchen221**
Closes #44

### Summary of Changes

feat: Added `Table.list_columns_with_missing_values`

### CODE REVIEW

**Comment by Marsmaennchen221** [comment]
I dont think the other changed requested in #44 make sense anymore. The requested `OptionalColumnType` is now implemented with the nullable types. The logic that converts "normal" columns into "nullable" columns when adding a missing value is implemented. 
I would leave the method `Column.has_missing_values` as it is now because with the `ColumnType` we only know that the column **could** contain missing values not that it has those in its current state.
If wanted we can add a different method `Column.could_contain_missing_values` but I am not sure if this is needed.

@lars-reimann Your thoughts?

**Comment by lars-reimann** [comment]
> I dont think the other changed requested in #44 make sense anymore. The requested `OptionalColumnType` is now implemented with the nullable types. The logic that converts "normal" columns into "nullable" columns when adding a missing value is implemented. I would leave the method `Column.has_missing_values` as it is now because with the `ColumnType` we only know that the column **could** contain missing values not that it has those in its current state. If wanted we can add a different method `Column.could_contain_missing_values` but I am not sure if this is needed.
> 
> @lars-reimann Your thoughts?

Let's move this discussion to #44.

**Review by jxnior01 — APPROVED** [review]
LGTM :D

**Comment by Marsmaennchen221** [comment]
> > I dont think the other changed requested in #44 make sense anymore. The requested `OptionalColumnType` is now implemented with the nullable types. The logic that converts "normal" columns into "nullable" columns when adding a missing value is implemented. I would leave the method `Column.has_missing_values` as it is now because with the `ColumnType` we only know that the column **could** contain missing values not that it has those in its current state. If wanted we can add a different method `Column.could_contain_missing_values` but I am not sure if this is needed.
> > @lars-reimann Your thoughts?
> 
> Let's move this discussion to #44.

I will leave this pr as a draft for now until we have solved this discussion

**Comment by lars-reimann** [comment]
Closing this, because the main branch has heavily diverged from this one.

**Pull request closed without merging**
