### PR TITLE
fix: rotation of xTicks and updated snapshots

### LINKED ISSUE #871: Unreadable labels of correlation heatmap
### Describe the bug

The x-labels of a correlation heatmap overlap, which greatly reduces readability. The y-labels are partially cut off.

### To Reproduce

Check the [tutorial for data visualization](https://library.safeds.com/en/latest/tutorials/data_visualization/#correlation-heatmap):

Untitled

### Expected behavior

Labels should be readable, e.g. by rotating them 90 degrees and ensuring that the created image is large enough.

### Screenshots (optional)

_No response_

### Additional Context (optional)

_No response_

### PR DESCRIPTION
**Pull request by Muellersen**
Closes #871 

### Summary of Changes

This pull request applies the correlation_heatmap ticks fix. We corrected the correlation_heatmap by rotating the xTicks by 90 degrees. This change also fixed the yTicks cutoff.

### CODE REVIEW

**Review by lars-reimann — CHANGES_REQUESTED** [review]
Why were all CUDA snapshots deleted in this PR? Please revert that change.

**Comment by Muellersen** [comment]
> Why were all CUDA snapshots deleted in this PR? Please revert that change.

The rotation of the xTicks also fixed the yTicks cutoff. I forgot to mention that.
We updated the snapshots with pytest --snapshot-update. After that we ran every test again, successfully.
Shall we still revert that change?

**Comment by Muellersen** [comment]
> Why were all CUDA snapshots deleted in this PR? Please revert that change.

The rotation of the xTicks also fixed the yTicks cutoff. I forgot to mention that.
We updated the snapshots with pytest --snapshot-update. After that we ran every test again, successfully.
Shall we still revert that change?

**Comment by lars-reimann** [comment]
> > Why were all CUDA snapshots deleted in this PR? Please revert that change.
> 
> The rotation of the xTicks also fixed the yTicks cutoff. I forgot to mention that. We updated the snapshots with pytest --snapshot-update. After that we ran every test again, successfully. Shall we still revert that change?

It's the correct way to update the snapshot, yes. Since you probably don't have a CUDA-capable GPU in your laptop, this also deletes all the CUDA snapshots, though. You should only commit the changes to the snapshots affected by the change in this PR and leave the CUDA-snapshots in the repo.

**Comment by Muellersen** [comment]
> > > Why were all CUDA snapshots deleted in this PR? Please revert that change.
> > 
> > 
> > The rotation of the xTicks also fixed the yTicks cutoff. I forgot to mention that. We updated the snapshots with pytest --snapshot-update. After that we ran every test again, successfully. Shall we still revert that change?
> 
> It's the correct way to update the snapshot, yes. Since you probably don't have a CUDA-capable GPU in your laptop, this also deletes all the CUDA snapshots, though. You should only commit the changes to the snapshots affected by the change in this PR and leave the CUDA-snapshots in the repo.

Alright, thanks you for explaning, we will revert the changes.

**Comment by lars-reimann** [comment]
It would also be helpful to have a test that reproduces the cutoff labels before your fix is applied.

**Comment by lars-reimann** [comment]
The old snapshots aren't back yet:

image

**Comment by Muellersen** [comment]
Git is causing some problems while reverting the changes, we will fix this next friday :)

**Review by lars-reimann — APPROVED** [review]
👍

**Pull request merged**
