### PR TITLE
build: use numpy<2.0.0

### PR DESCRIPTION
**Pull request by Marsmaennchen221**
### Summary of Changes

Add clause to `pyproject.toml` to use a numpy version below 2.0 as torchvision does not yet support numpy 2.0 (See #898)

### CODE REVIEW

**Comment by lars-reimann** [comment]
Why do we need to pin the version of transitive dependencies? Doesn't torchvision declare itself that it needs major version 1 for numpy?

**Comment by Marsmaennchen221** [comment]
> Why do we need to pin the version of transitive dependencies? Doesn't torchvision declare itself that it needs major version 1 for numpy?

torchvision does not specify any restrictions on the numpy version and as of pytorch version 2.3.0 pytorch does support numpy v2.0. While torchvision claims to be 98% compatible to Numpy v2.0, a few important methods like `read_image` or `save_image` do not support v2.0. So if you install the most recent version of safe-ds you will get numpy 2.0, but a few key methods like `Image.from_file` will not work.

**Comment by lars-reimann** [comment]
> torchvision does not specify any restrictions on the numpy version

😠

**Review by lars-reimann — APPROVED** [review]

**Pull request merged**
