### PR TITLE
build: Add Python 3.12 support

### PR DESCRIPTION
**Pull request by Marsmaennchen221**
### Summary of Changes

Add Python 3.12 support
Update used cuda Version to 12.1
Update PyTorch to Version 2.2
Update TorchVision to Version 0.17

### CODE REVIEW

**Review by lars-reimann — APPROVED** [review]
Excellent, thank you. `poetry-with-codecov (3.12)` is now also a required check again.

**Comment by WinPlay02** [comment]
@lars-reimann May I request a release of the library, to update the runner to be able to use python 3.12 again?

**Comment by lars-reimann** [comment]
> @lars-reimann May I request a release of the library, to update the runner to be able to use python 3.12 again?

Sure, it should be done in a few minutes.

**Pull request merged**
